### ISSUE TITLE
join forces?

### ISSUE THREAD

**Issue by razum2um** [mikejholly/crapidocs#2]
Hi. I'm author of http://lurker.razum2um.me/lurker/ and we have the same idea of "documentation from spec"
however lurker has a few differences:

Pro:
- further schema validation of test response
- internal use of json-schema
- html form gerenation like swagger does (mentioned in https://github.com/mikejholly/crapidocs/issues/1)
- interoperability with swagger via convertation
- standalone use/minitest support

Contra:
- need to annotate examples
- rails / action_dispatch bound

is that contra critical for you, or are there other contras?
so how can I help you or can we join forces otherwise?

**Comment by mikejholly** [comment]
Hm. Not needing to annotate anything was part of the motivation for writing this. I'm not sure that that will work.
